pinot/tracker_2d/filter_border: false
pinot/tracker_2d/update_votes: false

# clustering parameters
pinot/clustering/eps: 10
pinot/clustering/min_points: 5


# pnp ransac parameters
pinot/pose_estimation/use_ransac: false
pinot/pose_estimation/ransac_iterations: 100
pinot/pose_estimation/ransac_distance: 1.0
pinot/pose_estimation/ransac_method: 1 # 1: CV_ITERATIVE, 2: CV_P3P, 3: CV_EPNP

# offline parameters
pinot/offline/use_depth: false
# uncomment "pinot/offline/data_path:" and set it to the path where the pinot/offline/rgb_input: is located.
# otherwise the default data path is taken. Path should have the format /path_to_file/
# pinot/offline/data_path: /path_to_file/
pinot/offline/rgb_input: juice.avi
pinot/offline/depth_input: test_d.avi
pinot/offline/box_x: 131
pinot/offline/box_y: 50
pinot/offline/box_w: 36
pinot/offline/box_h: 89
pinot/offline/video_result: out.avi

# estimation of the size
pinot/cuboid/estimate_size: true

# debug and testing
pinot/results/save_output: true
pinot/results/output_path: /home/alessandro/Debug/






